webpack-contrib/less-loader

- .editorconfig
- index.js
- test/css/sourcemap.css
- test/index.test.js
- test/less/sourcemap.less
> Configure Less to create source maps

- README.md
For rookies it's easy to know how to install this loader.
> add installation hint

- README.md
Added missing closing bracket.
> Missing closing ]

- src/createWebpackLessPlugin.js
- src/formatLessError.js
- src/getOptions.js
- src/index.js
- src/processResult.js
> refactor: Split loader into separate modules

- package.json
> chore: fix package.json issues

- package-lock.json
- package.json
Just update `pify`, no breaking changes.
> chore(package): update `pify` v2.3.0...3.0.0

- babel.config.js
- package-lock.json
- package.json
Return nodejs and webpack version
Already done
No
> chore: return nodejs and webpack version

- package.json
BREAKING CHANGE: 2 version of less is not supported anymore
2 version of less is not supported anymore
Yes
No
> chore: drop less@2

- src/createWebpackLessPlugin.js
- test/fixtures/less/import-keyword-url.less
- test/index.test.js
> fix: import files hosted remotely

- test/fixtures/less/import-keyword-url.less
> test: import files hosted remotely

- package-lock.json
- package.json
- src/createWebpackLessPlugin.js
- test/__snapshots__/index.test.js.snap
- test/fixtures/less/import-webpack-aliases.less
- test/helpers/createSpec.js
- test/helpers/getErrors.js
- test/helpers/normalizeErrors.js
- test/index.test.js
import alias without tilda
No
No
> fix: import alias without tilde

- README.md
- package.json
Deleting a mention about less@2
No
No
> chore: deleting a mention about less2

- test/fixtures/less/folder/nested.less
- test/fixtures/less/import-nested.less
- test/index.test.js
add test for nested import
No
No
> test: import nested

- test/fixtures/less/folder/customImportPlugin.js
- test/index.test.js
import content through plugin
No
No
> test: import through plugin

- src/createWebpackLessPlugin.js
- test/__snapshots__/index.test.js.snap
- test/fixtures/less/import-scope.less
- test/fixtures/node_modules/@scope/css.css
- test/fixtures/node_modules/@scope/module.less
- test/helpers/createSpec.js
- test/index.test.js
import from scoped npm packages
No
No
> refactor: import from scoped npm packages

- test/helpers/index.js
- test/helpers/validateDependencies.js
- test/loader.test.js
Add validateDependencies to tests
No
No
> test: code

- .gitignore
- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/import-absolute-2.less
- test/fixtures/import-absolute-3.less
- test/helpers/getCodeFromLess.js
- test/loader.test.js
Resolve absolute url relative rootContext
No
No
> fix: resolve absolute url relative rootContext

- .gitignore
- src/index.js
- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/import-url-deps.less
- test/loader.test.js
> Fix remove urls todependensies

- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/import-non-less-2.less
- test/helpers/getCodeFromLess.js
- test/loader.test.js
> fix: restrictions

- README.md
- src/options.json
- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/__snapshots__/webpackImporter-options.test.js.snap
- test/loader.test.js
- test/validate-options.test.js
- test/webpackImporter-options.test.js
Add `webpackImporter` option for enables/disables the default Webpack importer
No
No
> Add webpackImporter option

- package-lock.json
- package.json
- src/utils.js
- test/loader.test.js
migrate on `klona` (faster and better)
Hope, no
No
> chore: migrate on `klona/full`

- src/LessError.js
- src/index.js
- src/utils.js
- test/__snapshots__/additionalData-option.test.js.snap
- test/__snapshots__/sourceMap-options.test.js.snap
- test/__snapshots__/webpackImporter-options.test.js.snap
- test/additionalData-option.test.js
- test/helpers/getCodeFromLess.js
- test/sourceMap-options.test.js
- test/webpackImporter-options.test.js
refactor code + tests + fix source map generation
No, loader is now async, but it was always private API
No
> Fix source map

- README.md
remove unused option `appendData` from readme
No
No
> docs: remove unused option from readme

- test/__snapshots__/loader.test.js.snap
- test/fixtures/import-relative.less
- test/loader.test.js
Add tests for lessOptions.relativeUrls
No
No
> Add tests for lessOptions.relativeUrls

- test/__snapshots__/loader.test.js.snap
The version of the google-font has changed.
When resolving google-fonts, the current version of the font differs from the one saved in the snapshot.
No
No
> test: update snapshot

- test/__snapshots__/loader.test.js.snap
Snapshot test failed and snapshots was updated
Snapshot test succeeded
> test: update snapshots

- package-lock.json
- package.json
`less 4.0.0` has been released and adds this version to `peerDependencies`.
less ^4.0 becomes available
https://github.com/less/less.js/releases/tag/v4.0.0
> chore: add less ^4.0 to peerDependencies

- src/LessError.js
- src/index.js
fixes #400
No
Some plugins can change error message and remove the `filename` property
> fix: errors from less

- test/loader.test.js
> test: uncomment

- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/by-dependency.less
- test/fixtures/circular.less
- test/fixtures/custom-main-files/custom.less
- test/helpers/getCodeFromLess.js
- test/loader.test.js
it is good features :smile: 
No
No
> feat: supported by dependency

- package-lock.json
- package.json
- test/__snapshots__/loader.test.js.snap
update deps + fix `prepare` for husky
No
No
> chore(deps): update

- README.md
- src/index.js
- src/options.json
- src/utils.js
- test/__snapshots__/implementation.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/implementation.test.js
- test/validate-options.test.js
> feat: implementation option string support added

- package-lock.json
- package.json
- src/index.js
- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/loader.test.js
fix memory usage
Yes
https://github.com/webpack/webpack/issues/13127#issuecomment-863091357
> fix: memory usage

- .github/workflows/nodejs.yml
> chore: migrate to `setup-node/v2`

- lint-staged.config.js
- test/__snapshots__/loader.test.js.snap
> chore: expand lint-staged, use eslint cache

- .github/workflows/nodejs.yml
- test/__snapshots__/loader.test.js.snap
- test/loader.test.js
> chore: add node 18 and update snapshot

- .github/workflows/nodejs.yml
- babel.config.js
- package-lock.json
- package.json
> refactor!: minimum supported `Node.js` version is `14.15.0`

- README.md
> chore: remove old badge

- README.md
remove deprecated instructions
No
No
> docs: remove deprecated instructions

- package-lock.json
- package.json
- test/__snapshots__/additionalData-option.test.js.snap
- test/__snapshots__/implementation.test.js.snap
- test/__snapshots__/loader.test.js.snap
- test/__snapshots__/sourceMap-options.test.js.snap
- test/__snapshots__/webpackImporter-options.test.js.snap
update jest to the latest version
No
No
> chore: update jest to the latest version

- README.md
> docs: fix outdated broken link

- .github/workflows/nodejs.yml
> ci: node v24
