- README.md
- index.js
- test/index.test.js
Since version 2 of less, Clean CSS is no longer bundled but has to be used as a plugin http://lesscss.org/usage/#command-line-usage-compress. The query-string configuration of less-loader is insufficient to pass plugin instances to less.
This change allows for plugins to be passed to less as specified here: http://lesscss.org/usage/#plugins-using-a-plugin-in-code.
> Provide support for lesscss plugins

- README.md
There are certain options on `lessc` which don't precisely map to the implied syntax in the docs (e.g. `lessc --modifyVar="myVar=myVal"` actually maps to `style!css!less?{"modifyVars":{"myVar":"myVal"}}`). This update clarifies the documentation.
> Disambiguate Query Parameter Docs

- index.js
- test/css/data-uri.css
- test/css/imports-bower.css
- test/css/imports-node.css
- test/index.test.js
- test/less/data-uri.less
- test/less/resources/circle.svg
Fix issue #38 :
```
Module build failed: error evaluating function `data-uri`: Cannot 'resolveSync' because the fileSystem is not sync. Use 'resolve'!
```
> Fix data-uri (issue #38)

- .travis.yml
- package.json
npm@3 remove `peerDependencies` support now.
> Use dependencies instead of peerDependencies.

- index.js
Path information was lost from the source map due to `path.basename()` being run for each file in the source map. I'm not sure why this piece of code was there, but everything seems to be working fine after removing it.
Here's how the source map generated by `npm run test-source-map` looks now in Chrome developer tools:
Before:
After:
> Fix source map missing path information

- README.md
Summary:
----
Webpack v2.1.0-beta.26 introduced a breaking change to require loaders to have the `-loader` suffix. 
This PR updates the README to show that pattern as an example instead of using the shorthand naming.
cc: @sokra @jhnns
> Update README with -loader suffix for all examples to reflect webpack 2 changes

- README.md
Referencing issue #109 it seems like this is something worth including in the README? Feel free to close the PR if unnecessary but if people are using CSS modules, they should be aware of that issue.
> Updated README regarding relative filepaths issue

- README.md
Just added the comma for the "copy/paste" code warriors. :)
> Missing comma in example

- README.md
file change:
./README.md
updates:
fix obviously missing comma in README document
> fix obviously missing comma in README

- README.md
[As you ask me)](https://github.com/webpack-contrib/sass-loader/pull/405)
But docs page already fixed and don't show images and custom html tags :(
> Adding link to maintainer image

- src/createWebpackLessPlugin.js
* Use class syntax
* Use promises. They are already supported by less 2.1.1
> refactor(less-plugin)

- package.json
BREAKING CHANGE: Require webpack 2 as peer dependency
> chore(dependencies): Update peer dependencies

- package.json
> Use `dist/index.js` as the package's entry point

- package.json
- src/getOptions.js
- test/index.test.js
- yarn.lock
clone-deep does not clone properties from the prototype chain, see https://github.com/webpack-contrib/less-loader/issues/181#issuecomment-288220113
> fix: Plugin.install is not a function

- src/getOptions.js
- test/helpers/createSpec.js
- test/index.test.js
less-loader 4 did not automatically apply the sourceMap.outputSourceFiles option anymore. This led to a situation where source maps didn't work out of the box anymore (while it still was possible to set this option manually).
Fixes #183
> fix: sourcesContent missing in source maps

- README.md
This is required for inclusion at https://webpack.js.org/loaders/less-loader/. Currently, the hyperlink CI check fails ([example](https://travis-ci.org/webpack/webpack.js.org/builds/228533163#L783)).
> docs(README): absolute link to example

- .babelrc
- .github/ISSUE_TEMPLATE.md
- appveyor.yml
- package.json
- yarn.lock
- Update resolves babelrc recommendation spam
- Updates Jest to v20
- Tweaks appveyor configuration
> chore(package): Update to webpack-defaults 1.0.1

- .babelrc
- .travis.yml
- appveyor.yml
- package-lock.json
- package.json
Now node 8.2 is stable these hacks I added in https://github.com/webpack-contrib/less-loader/pull/208 can be removed. Doing `npm i` on a fresh checkout of the repo somehow updated the package-lock as well which was a bit odd.
edit: looks like appveyor is still on node 8.1 which has the buggy npm 5.0.x, will have to wait a bit for them to upgrade. Can use https://www.appveyor.com/updates/ for tracking when node 8.2.x is added.
> chore: Update to webpack-defaults 1.6

- package.json
Adds webpack 4 as an allowed peer dependency
Had to fix the dev dependency of webpack to `^3.10.0` (matches uglify plugin) otherwise the tests would use latest and fail as `mode` was not set in the config.
> fix(package): add `webpack >= v4.0.0`  (`peerDependencies`)

- README.md
Following the conventions from https://webpack.js.org/writers-guide/#typesetting
> docs(README): typesetting of loaders and plugins

- package-lock.json
- package.json
- src/createWebpackLessPlugin.js
- test/__snapshots__/index.test.js.snap
- test/fixtures/less/import-url.less
- test/index.test.js
> feat(package): support `less >= v3.0.0`

- .babelrc
- package.json
This PRs only removes some old left bits pointing to node < 6 and webpack < 4 versions.
/CC @evilebottnawi
> Drop support for node < 6 and webpack < 4

- src/processResult.js
> fix: webpack watching does not recover after broken less is fixed

- .eslintignore
- azure-pipelines.yml
- lint-staged.config.js
- package-lock.json
- package.json
https://github.com/webpack-contrib/less-loader/issues/307
The first step towards the new version! - updating dependencies
I updated the required dependencies at a safe level. Didn't experienced any breaking changes except for lint-staged. which has removed advanced config options. So moved the ignore options to `.eslintignore` file recommenend by the team https://github.com/okonet/lint-staged#ignoring-files. 
Added support for node version `v10.13.0`
> chore: updated dependencies safely and made lint staged config changes

- src/getOptions.js
Less options filename should be filled with a resourcePath without resourceQuery, in some case when a root less resource is requested with a query, filling filename with query may yield a resolve error when less core resolving other refered less resource.
A simple example
main.js
```js
import './a.less?someQueryWithPath=/user/xxx/xxx'
```
a.less
```less
@import './b.less'
.a { color: red; }
```
b.less
```less
.b { color: green; }
```
Simply running webpack with entry `main.js`, an error will occur when resolving `./b.less`.
> fix: fill less `options.filename` with `loaderContext.resourcePath` instead of `loaderContext.resource`

- src/index.js
- src/processResult.js
Remove the sync check and pass through the `loaderContext.callback` from `this.async`
> chore: remove sync check

- package-lock.json
- package.json
- src/createWebpackLessPlugin.js
- src/index.js
- test/helpers/readFixture.js
Remove `pify` in favour of the native `promisify` function from the `util` library
> chore: remove `pify` in favour of `util.promisify`

- README.md
- src/getLessOptions.js
- src/options.json
- test/index.test.js
Allow a function to be passed through for `lessOptions`, being called with the loader's context. Matches what `sass-loader` allows.
> feat: allow a function to be used for `lessOptions`

- README.md
Add a functional example for using a function when passing `lessOptions`.
> docs(readme): add example for `lessOptions` using a function

- README.md
- src/getLessOptions.js
- src/index.js
- src/options.json
- test/fixtures/less/prepend-data.less
- test/index.test.js
Add the `prependData` option that `sass-loader` offers
> feat: allow data to be prepended via `options.prependData`

- README.md
- src/getLessOptions.js
- src/options.json
- test/fixtures/less/append-data.less
- test/index.test.js
> feat: add appendData option

- test/index.test.js
appendData prependData, when they are string
No
No
> test: appendData prependData, when they are string

- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/file-load-replacement.less
- test/fixtures/file-load.less
- test/fixtures/folder/customFileLoaderPlugin.js
- test/helpers/getCodeFromLess.js
- test/loader.test.js
> fix: work third-party plugins as fileLoader

- README.md
- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/basic-plugins.less
- test/fixtures/plugin-1.js
- test/loader.test.js
Add loader context in less plugins
Loader context is available in `less.webpackLoaderContext`
No
No
> Add loader context in less plugins

- README.md
> docs: removed deprecated info

- src/index.js
This allows the result of `additionalData` to be a Promise.
This is especially useful if you want to use `loaderContext.resolve` to get additional data through the standard webpack mechanisms.
none
n/a
> allow additionalData to be async

- README.md
When I first load the webpack , an error occured:
```
ERROR in ./src/big.less 1:5
Module parse failed: Unexpected token (1:5)
File was processed with these loaders:
* ./node_modules/less-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
> body div {
|   font-size: 200px;
| }
@ ./src/index.js 6:0-20
```
> docs: update loader

- README.md
- src/index.js
- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/basic-plugins-2.less
- test/fixtures/plugin-2.js
- test/loader.test.js
Deprecated `less.webpackLoaderContext`.
Added `pluginManager.webpackLoaderContext`.
No
No
> fix: memory leak

- src/index.js
- src/utils.js
> fix: deprecation warning

- README.md
Currently the example shows `loader` instead of `use` which will not work with Webpack 5
> fix less-loader example: replace `loader` with `use`

- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/import-package-with-exports-and-custom-condition.less
- test/fixtures/node_modules/package-with-exports-and-custom-condition/index.cjs
- test/fixtures/node_modules/package-with-exports-and-custom-condition/index.js
- test/fixtures/node_modules/package-with-exports-and-custom-condition/package.json
- test/fixtures/node_modules/package-with-exports-and-custom-condition/style-1.less
- test/fixtures/node_modules/package-with-exports-and-custom-condition/style-2.less
- test/helpers/getCodeFromLess.js
- test/loader.test.js
> feat: allow to extend `conditionNames`

- src/index.js
- src/utils.js
- test/__snapshots__/implementation.test.js.snap
- test/fixtures/implementation-error.js
- test/implementation.test.js
part of https://github.com/webpack/webpack/issues/15980
No
No
> fix: handling error better

- package.json
- src/utils.js
- test/loader.test.js
Better perf and less deps
No
We need only plugins, so we need to clone only this
> fix(perf): avoid using `klona` for `less` options

- test/__snapshots__/loader.test.js.snap
- test/fixtures/less-package.less
- test/fixtures/node_modules/less-package-1/index.less
- test/fixtures/node_modules/less-package-1/package.json
- test/fixtures/node_modules/less-package-2/index.less
- test/fixtures/node_modules/less-package-2/node_modules/less-package-1/index.less
- test/fixtures/node_modules/less-package-2/node_modules/less-package-1/package.json
- test/fixtures/node_modules/less-package-2/package.json
- test/helpers/getCodeFromLess.js
- test/loader.test.js
fixes https://github.com/webpack-contrib/less-loader/issues/524
No
Two tests to confirm we are resolving the right packages
> test: package resolving

- src/utils.js
- test/__snapshots__/loader.test.js.snap
- test/fixtures/3rd/b.less
- test/fixtures/resolve-working-directory/index.less
- test/fixtures/resolve-working-directory/resolve-working-directory-a.less
- test/helpers/getCodeFromLess.js
- test/loader.test.js
fixes https://github.com/webpack-contrib/less-loader/issues/512
No
No
> fix: invalid dependencies with working directory

- README.md
- src/index.js
- src/options.json
- test/__snapshots__/loader.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/fixtures/err.less
- test/fixtures/warn.less
- test/loader.test.js
- test/validate-options.test.js
https://github.com/webpack/webpack/discussions/17013
No
Let's set it to `true` by default in the next major release
> feat: added the `lessLogAsWarnOrErr` option

- README.md
- src/options.json
- src/utils.js
- test/__snapshots__/validate-options.test.js.snap
- test/__snapshots__/webpackImporter-options.test.js.snap
- test/validate-options.test.js
- test/webpackImporter-options.test.js
When using the `resolve.extensionAlias` property in `webpack` or `rspack`, the built-in importer of less-loader would cause this property to become ineffective. Therefore, we've added an `onlyWebpackImporter` option to enable this capability.
No breaking change
No additional info
> feat: Add support for using only webpackImporter
